const CATEGORIES = [
{id:'government',glyph:'🏛',name:'Government',desc:'The executive and legislative machinery — offices, ministries, gazettes and the record of Parliament itself.',
 sources:[
  {n:'Prime Minister\'s Office',d:'Statements, schemes and the official record of the PM\'s office.',u:'https://www.pmindia.gov.in'},
  {n:'President of India',d:'Addresses, appointments and the constitutional head of state.',u:'https://presidentofindia.nic.in'},
  {n:'Vice President of India',d:'Official communications and functions of the Vice President.',u:'https://vicepresidentofindia.nic.in'},
  {n:'Cabinet Secretariat',d:'Decisions of the Union Cabinet and coordination across ministries.',u:'https://cabsec.gov.in'},
  {n:'India.gov.in — National Portal',d:'The single directory of every union ministry, department and service.',u:'https://www.india.gov.in'},
  {n:'Press Information Bureau',d:'Official government press releases, the day these things actually happen.',u:'https://pib.gov.in'},
  {n:'MyGov',d:'Citizen engagement platform for policy consultations and campaigns.',u:'https://www.mygov.in'},
  {n:'Open Government Data Platform',d:'Government of India\'s open data platform across every sector.',u:'https://data.gov.in'},
  {n:'Lok Sabha',d:'Debates, bills, questions and proceedings of the lower house.',u:'https://sansad.in/ls'},
  {n:'Rajya Sabha',d:'Debates, bills and proceedings of the upper house.',u:'https://sansad.in/rs'},
  {n:'PRS Legislative Research',d:'Independent, rigorous analysis of bills and parliamentary functioning.',u:'https://prsindia.org'},
  {n:'India Code',d:'The official digital repository of all central and state legislation.',u:'https://www.indiacode.nic.in'},
  {n:'e-Gazette of India',d:'Official notifications, orders and statutory publications.',u:'https://egazette.gov.in'},
  {n:'Ministry of Home Affairs',d:'Internal security, states, union territories and civil administration.',u:'https://www.mha.gov.in'},
  {n:'Ministry of External Affairs',d:'India\'s foreign policy, treaties and diplomatic record.',u:'https://www.mea.gov.in'},
  {n:'Ministry of Defence',d:'Defence policy, procurement and the armed forces establishment.',u:'https://www.mod.gov.in'},
  {n:'Ministry of Finance',d:'Fiscal policy, budget documents and departmental notifications.',u:'https://www.finmin.nic.in'},
  {n:'Ministry of Law and Justice',d:'Legislation drafting, legal affairs and justice administration.',u:'https://lawmin.gov.in'},
  {n:'Department of Personnel & Training',d:'Civil services recruitment, rules and administrative reform.',u:'https://dopt.gov.in'},
  {n:'NITI Aayog',d:'Policy think tank driving India\'s development strategy.',u:'https://www.niti.gov.in'},
  {n:'UIDAI',d:'Authority managing Aadhaar enrolment, updates and authentication.',u:'https://uidai.gov.in'},
  {n:'Central Vigilance Commission',d:'Apex body overseeing integrity in government administration.',u:'https://cvc.gov.in'},
  {n:'Central Information Commission',d:'Appellate authority for Right to Information Act cases.',u:'https://cic.gov.in'},
  {n:'National Human Rights Commission',d:'Statutory body investigating human rights violations.',u:'https://nhrc.nic.in'},
  {n:'Ministry of Electronics & IT',d:'Digital governance, IT policy and electronics manufacturing.',u:'https://www.meity.gov.in'},
  {n:'Dept. of Administrative Reforms & PG',d:'Governance reform and public grievance redress.',u:'https://darpg.gov.in'},
  {n:'Digital India',d:'Flagship programme for a digitally empowered society.',u:'https://www.digitalindia.gov.in'},
  {n:'UMANG',d:'Unified mobile platform for government services and schemes.',u:'https://web.umang.gov.in'},
  {n:'Department of Posts',d:'India Post\'s official services and philately record.',u:'https://www.indiapost.gov.in'},
  {n:'National Informatics Centre',d:'Technology backbone behind most government digital platforms.',u:'https://www.nic.in'},
 ]},
{id:'education',glyph:'📚',name:'Education',desc:'The regulators, boards and testing bodies that set curricula, accreditation and standards.',
 sources:[
  {n:'Ministry of Education',d:'National education policy, schemes and school/higher-ed governance.',u:'https://www.education.gov.in'},
  {n:'University Grants Commission',d:'Regulator for university education standards and funding.',u:'https://www.ugc.gov.in'},
  {n:'NCERT',d:'National curriculum framework, textbooks and educational research.',u:'https://ncert.nic.in'},
  {n:'National Testing Agency',d:'Conducts JEE, NEET and other national entrance examinations.',u:'https://nta.ac.in'},
  {n:'CBSE',d:'Central Board of Secondary Education — syllabi, results, circulars.',u:'https://www.cbse.gov.in'},
  {n:'AICTE',d:'Regulator for technical and management education institutions.',u:'https://www.aicte-india.org'},
  {n:'NAAC',d:'Accreditation body assessing quality of higher education institutions.',u:'https://www.naac.gov.in'},
  {n:'NIRF',d:'National Institutional Ranking Framework — official college rankings.',u:'https://www.nirfindia.org'},
  {n:'NCTE',d:'National Council for Teacher Education — teacher training standards.',u:'https://ncte.gov.in'},
  {n:'IGNOU',d:'India\'s national open university for distance education.',u:'https://ignou.ac.in'},
  {n:'SWAYAM',d:'Government MOOC platform offering free courses from school to PG.',u:'https://swayam.gov.in'},
  {n:'DIKSHA',d:'National digital infrastructure for teachers and students.',u:'https://diksha.gov.in'},
  {n:'NIOS',d:'National Institute of Open Schooling — open school certification.',u:'https://www.nios.ac.in'},
  {n:'NCVET',d:'Regulator for vocational education and skill certification.',u:'https://ncvet.gov.in'},
  {n:'CBSE Academic',d:'Curriculum, sample papers and academic circulars from CBSE.',u:'https://cbseacademic.nic.in'},
  {n:'Ministry of Skill Development',d:'National skilling policy and entrepreneurship schemes.',u:'https://www.msde.gov.in'},
  {n:'National Skill Development Corporation',d:'Public-private skilling initiatives and training partners.',u:'https://nsdcindia.org'},
  {n:'UNESCO Institute for Statistics',d:'Global benchmark education and literacy statistics.',u:'http://uis.unesco.org'},
  {n:'UNESCO — Education',d:'Global education policy, standards and Sustainable Development Goal 4.',u:'https://www.unesco.org/en/education'},
  {n:'World Bank — Education',d:'Research, financing and data on education systems worldwide.',u:'https://www.worldbank.org/en/topic/education'},
  {n:'OECD — Education',d:'PISA rankings and comparative education policy analysis.',u:'https://www.oecd.org/en/topics/education.html'},
  {n:'UNICEF — Education',d:'Child education access, equity and learning outcomes data.',u:'https://www.unicef.org/education'},
  {n:'ASER Centre',d:'Annual Status of Education Report — rural learning outcomes.',u:'https://asercentre.org'},
  {n:'National Digital Library of India',d:'Aggregated academic content across formats and languages.',u:'https://ndl.iitkgp.ac.in'},
  {n:'Rashtriya Uchchatar Shiksha Abhiyan',d:'Centrally sponsored scheme for state higher-education reform.',u:'https://rusa.nic.in'},
  {n:'Central Institute of Educational Technology',d:'NCERT\'s wing for ed-tech and educational broadcasting.',u:'https://ciet.nic.in'},
  {n:'UNESCO IIEP',d:'International Institute for Educational Planning research.',u:'https://www.iiep.unesco.org'},
  {n:'Global Partnership for Education',d:'Multilateral fund and partnership for education in developing countries.',u:'https://www.globalpartnership.org'},
  {n:'European Education Area',d:'EU policy cooperation on education and training.',u:'https://education.ec.europa.eu'},
  {n:'U.S. Department of Education',d:'Federal education policy, data and student aid.',u:'https://www.ed.gov'},
 ]},
{id:'economy',glyph:'💰',name:'Economy',desc:'Monetary policy, public finance, capital markets and the statistical backbone of the economy.',
 sources:[
  {n:'Reserve Bank of India',d:'Monetary policy, inflation data, banking regulation and reports.',u:'https://www.rbi.org.in'},
  {n:'Ministry of Finance',d:'Fiscal policy, budget documents and departmental notifications.',u:'https://www.finmin.nic.in'},
  {n:'Economic Survey',d:'The government\'s annual flagship review of the Indian economy.',u:'https://www.indiabudget.gov.in/economicsurvey/'},
  {n:'Union Budget',d:'Budget speeches, expenditure and receipt documents, year on year.',u:'https://www.indiabudget.gov.in'},
  {n:'SEBI',d:'Securities market regulator — orders, circulars and investor data.',u:'https://www.sebi.gov.in'},
  {n:'NABARD',d:'Apex bank for agriculture and rural development finance.',u:'https://www.nabard.org'},
  {n:'MOSPI',d:'Ministry of Statistics — GDP, inflation and national accounts data.',u:'https://www.mospi.gov.in'},
  {n:'NITI Aayog',d:'Policy think tank driving India\'s development strategy.',u:'https://www.niti.gov.in'},
  {n:'Department of Economic Affairs',d:'Macroeconomic policy, capital markets and multilateral finance.',u:'https://dea.gov.in'},
  {n:'Department of Revenue',d:'Direct and indirect tax policy administration.',u:'https://dor.gov.in'},
  {n:'Income Tax Department',d:'Direct tax filing, refunds and taxpayer services.',u:'https://www.incometax.gov.in'},
  {n:'GST Portal',d:'Goods and Services Tax registration, returns and rules.',u:'https://www.gst.gov.in'},
  {n:'CBIC',d:'Central Board of Indirect Taxes and Customs — duty and customs rules.',u:'https://www.cbic.gov.in'},
  {n:'Insolvency and Bankruptcy Board of India',d:'Regulator for India\'s insolvency resolution framework.',u:'https://ibbi.gov.in'},
  {n:'IRDAI',d:'Insurance sector regulator — policies, circulars, data.',u:'https://irdai.gov.in'},
  {n:'PFRDA',d:'Pension Fund Regulatory and Development Authority.',u:'https://www.pfrda.org.in'},
  {n:'Competition Commission of India',d:'Antitrust enforcement and market competition orders.',u:'https://www.cci.gov.in'},
  {n:'National Stock Exchange',d:'Market data, filings and listed company disclosures.',u:'https://www.nseindia.com'},
  {n:'Bombay Stock Exchange',d:'India\'s oldest exchange — filings, indices and disclosures.',u:'https://www.bseindia.com'},
  {n:'DPIIT',d:'Industrial policy, startup ecosystem and FDI regulation.',u:'https://dpiit.gov.in'},
  {n:'Ministry of Commerce & Industry',d:'Trade policy, exports and industrial development.',u:'https://commerce.gov.in'},
  {n:'DGFT',d:'Directorate General of Foreign Trade — export-import policy.',u:'https://www.dgft.gov.in'},
  {n:'SIDBI',d:'Small Industries Development Bank of India — MSME finance.',u:'https://www.sidbi.in'},
  {n:'EPFO',d:'Employees\' Provident Fund Organisation — retirement savings.',u:'https://www.epfindia.gov.in'},
  {n:'World Bank',d:'Development finance, country data and global economic reports.',u:'https://www.worldbank.org'},
  {n:'International Monetary Fund',d:'Global macroeconomic surveillance, lending and financial stability.',u:'https://www.imf.org'},
  {n:'Asian Development Bank',d:'Regional development finance and economic research for Asia.',u:'https://www.adb.org'},
  {n:'Bank for International Settlements',d:'Central bank cooperation and global financial stability data.',u:'https://www.bis.org'},
  {n:'NPCI',d:'National Payments Corporation of India — UPI and digital payments infrastructure.',u:'https://www.npci.org.in'},
  {n:'Controller General of Accounts',d:'Government accounting and monthly fiscal reporting.',u:'https://cga.nic.in'},
 ]},
{id:'election',glyph:'🗳',name:'Election',desc:'The constitutional bodies, disclosures and global institutions that govern how democracies vote.',
 sources:[
  {n:'Election Commission of India',d:'Conduct of elections, model code of conduct, official notifications.',u:'https://eci.gov.in'},
  {n:'ECI Results',d:'Official, constituency-wise results as declared by the Commission.',u:'https://results.eci.gov.in'},
  {n:'Candidate Affidavits (ECI)',d:'Sworn asset, criminal-case and education disclosures of candidates.',u:'https://affidavit.eci.gov.in'},
  {n:'Voter Services Portal',d:'Voter registration, e-EPIC and roll search.',u:'https://voters.eci.gov.in'},
  {n:'MyNeta (ADR)',d:'Searchable, structured database of candidate affidavits and criminal cases.',u:'https://myneta.info'},
  {n:'Association for Democratic Reforms',d:'India\'s leading electoral transparency and accountability NGO.',u:'https://adrindia.org'},
  {n:'Political Party Registration (ECI)',d:'Official list and status of recognised and registered parties.',u:'https://eci.gov.in/political-parties-home/'},
  {n:'International IDEA',d:'Global institute for democracy and electoral assistance.',u:'https://www.idea.int'},
  {n:'ACE Electoral Knowledge Network',d:'Comparative reference on electoral systems and administration.',u:'https://aceproject.org'},
  {n:'National Democratic Institute',d:'Election observation and democratic governance support worldwide.',u:'https://www.ndi.org'},
  {n:'The Carter Center',d:'Independent election observation and conflict resolution.',u:'https://www.cartercenter.org'},
  {n:'IFES',d:'International Foundation for Electoral Systems — election administration.',u:'https://www.ifes.org'},
  {n:'EU Election Observation & Democracy Support',d:'European Union\'s election observation missions worldwide.',u:'https://www.eods.eu'},
  {n:'Inter-Parliamentary Union',d:'Global organisation of national parliaments.',u:'https://www.ipu.org'},
  {n:'U.S. Federal Election Commission',d:'Campaign finance disclosure and federal election law.',u:'https://www.fec.gov'},
  {n:'UK Electoral Commission',d:'Regulator of UK elections and political finance.',u:'https://www.electoralcommission.org.uk'},
  {n:'Australian Electoral Commission',d:'Conducts and regulates Australian federal elections.',u:'https://www.aec.gov.au'},
  {n:'Election Commission of Pakistan',d:'Conducts and regulates elections in Pakistan.',u:'https://www.ecp.gov.pk'},
  {n:'Election Commission of Nepal',d:'Conducts and regulates elections in Nepal.',u:'https://election.gov.np'},
  {n:'Bangladesh Election Commission',d:'Conducts and regulates elections in Bangladesh.',u:'https://www.ecs.gov.bd'},
  {n:'Election Commission of Sri Lanka',d:'Conducts and regulates elections in Sri Lanka.',u:'https://elections.gov.lk'},
  {n:'Association of World Election Bodies',d:'Global network of election management bodies.',u:'https://www.aweb.org'},
  {n:'V-Dem Institute',d:'Academic project measuring democracy worldwide with granular data.',u:'https://v-dem.net'},
  {n:'Freedom House',d:'Annual assessments of political rights and civil liberties globally.',u:'https://freedomhouse.org'},
  {n:'OSCE / ODIHR',d:'Election monitoring and democratic institution-building in Europe/Central Asia.',u:'https://www.osce.org/odihr'},
  {n:'PRS Legislative Research',d:'Independent analysis of representation, bills and legislative conduct.',u:'https://prsindia.org'},
 ]},
{id:'judiciary',glyph:'⚖',name:'Judiciary',desc:'Courts, case-status systems and the bodies — domestic and international — that interpret and reform the law.',
 sources:[
  {n:'Supreme Court of India',d:'Judgments, cause lists and the apex constitutional court\'s record.',u:'https://www.sci.gov.in'},
  {n:'eCourts Services',d:'Case status, orders and judgments across district and high courts.',u:'https://ecourts.gov.in'},
  {n:'High Courts of India — Directory',d:'Directory linking to every state High Court\'s official site.',u:'https://ecourts.gov.in/ecourts_home/static/highcourts.php'},
  {n:'Law Commission of India',d:'Reports and recommendations on legal and judicial reform.',u:'https://lawcommissionofindia.nic.in'},
  {n:'National Judicial Data Grid',d:'Real-time case pendency and disposal data across courts.',u:'https://njdg.ecourts.gov.in'},
  {n:'Department of Justice',d:'Judicial infrastructure, appointments and access-to-justice schemes.',u:'https://doj.gov.in'},
  {n:'National Legal Services Authority',d:'Free legal aid and Lok Adalat framework across India.',u:'https://nalsa.gov.in'},
  {n:'Bar Council of India',d:'Regulator of legal education and the legal profession.',u:'https://www.barcouncilofindia.org'},
  {n:'Indian Kanoon',d:'Free, searchable repository of Indian case law and statutes.',u:'https://indiankanoon.org'},
  {n:'National Company Law Tribunal',d:'Adjudicates corporate, insolvency and company law disputes.',u:'https://nclt.gov.in'},
  {n:'Securities Appellate Tribunal',d:'Appeals against SEBI, IRDAI and PFRDA orders.',u:'https://www.sat.gov.in'},
  {n:'International Court of Justice',d:'The UN\'s principal judicial organ for inter-state disputes.',u:'https://www.icj-cij.org'},
  {n:'International Criminal Court',d:'Prosecutes genocide, war crimes and crimes against humanity.',u:'https://www.icc-cpi.int'},
  {n:'Permanent Court of Arbitration',d:'Resolves international disputes through arbitration.',u:'https://pca-cpa.org'},
  {n:'UN Office of Legal Affairs',d:'Custodian of treaties and international legal frameworks.',u:'https://legal.un.org'},
  {n:'European Court of Human Rights',d:'Adjudicates human rights complaints under the European Convention.',u:'https://www.echr.coe.int'},
  {n:'Supreme Court of the United States',d:'Opinions, oral arguments and docket of the U.S. apex court.',u:'https://www.supremecourt.gov'},
  {n:'Supreme Court of the United Kingdom',d:'Judgments of the UK\'s final court of appeal.',u:'https://www.supremecourt.uk'},
  {n:'World Justice Project',d:'Rule of Law Index and comparative legal-system data.',u:'https://worldjusticeproject.org'},
  {n:'UN Treaty Collection',d:'Official register of international treaties and their status.',u:'https://treaties.un.org'},
  {n:'Human Rights Watch',d:'Investigative reporting on rights violations and legal accountability.',u:'https://www.hrw.org'},
  {n:'Amnesty International',d:'Global human-rights research, campaigns and legal advocacy.',u:'https://www.amnesty.org'},
  {n:'International Bar Association',d:'Global professional body for lawyers and legal standards.',u:'https://www.ibanet.org'},
  {n:'UNCITRAL',d:'UN body harmonising international trade law.',u:'https://uncitral.un.org'},
 ]},
{id:'health',glyph:'🏥',name:'Health',desc:'Public health authorities, research bodies and the journals that set clinical evidence.',
 sources:[
  {n:'World Health Organization',d:'Global health guidance, outbreak data and technical reports.',u:'https://www.who.int'},
  {n:'Ministry of Health & Family Welfare',d:'India\'s national health policy, schemes and disease data.',u:'https://www.mohfw.gov.in'},
  {n:'ICMR',d:'Indian Council of Medical Research — clinical and biomedical research.',u:'https://www.icmr.gov.in'},
  {n:'National Health Mission',d:'Rural and urban health mission implementation and reports.',u:'https://nhm.gov.in'},
  {n:'NCDC',d:'National Centre for Disease Control — surveillance and outbreak response.',u:'https://ncdc.mohfw.gov.in'},
  {n:'UNICEF',d:'Child health, nutrition and survival data worldwide.',u:'https://www.unicef.org'},
  {n:'CDC (U.S.)',d:'Disease control guidance and epidemiological data.',u:'https://www.cdc.gov'},
  {n:'The Lancet',d:'Peer-reviewed general medical research journal.',u:'https://www.thelancet.com'},
  {n:'BMJ',d:'Peer-reviewed medical journal — research, analysis, guidelines.',u:'https://www.bmj.com'},
  {n:'Nature Medicine',d:'Peer-reviewed biomedical and clinical research journal.',u:'https://www.nature.com/nm/'},
  {n:'AIIMS',d:'India\'s premier public medical institution and research centre.',u:'https://www.aiims.edu'},
  {n:'CDSCO',d:'India\'s central drug regulatory authority.',u:'https://cdsco.gov.in'},
  {n:'NACO',d:'National AIDS Control Organisation — HIV/AIDS policy and data.',u:'https://naco.gov.in'},
  {n:'National Health Authority',d:'Implements Ayushman Bharat and India\'s digital health mission.',u:'https://nha.gov.in'},
  {n:'FSSAI',d:'Food Safety and Standards Authority of India — food regulation.',u:'https://www.fssai.gov.in'},
  {n:'National Institute of Nutrition',d:'ICMR body researching nutrition and dietary guidelines.',u:'https://www.nin.res.in'},
  {n:'U.S. National Institutes of Health',d:'Federal biomedical and public health research agency.',u:'https://www.nih.gov'},
  {n:'U.S. FDA',d:'Regulates drugs, vaccines and medical devices in the U.S.',u:'https://www.fda.gov'},
  {n:'European Medicines Agency',d:'EU regulator for medicines evaluation and safety.',u:'https://www.ema.europa.eu'},
  {n:'PubMed',d:'The National Library of Medicine\'s biomedical literature index.',u:'https://pubmed.ncbi.nlm.nih.gov'},
  {n:'Cochrane Library',d:'Systematic reviews — the gold standard of medical evidence.',u:'https://www.cochranelibrary.com'},
  {n:'JAMA',d:'Peer-reviewed journal of the American Medical Association.',u:'https://jamanetwork.com'},
  {n:'New England Journal of Medicine',d:'Leading peer-reviewed medical research journal.',u:'https://www.nejm.org'},
  {n:'UNAIDS',d:'Global data and policy coordination on HIV/AIDS.',u:'https://www.unaids.org'},
  {n:'The Global Fund',d:'Financing to fight AIDS, tuberculosis and malaria worldwide.',u:'https://www.theglobalfund.org'},
  {n:'Gavi, the Vaccine Alliance',d:'Global immunisation access and vaccine market data.',u:'https://www.gavi.org'},
  {n:'Institute for Health Metrics and Evaluation',d:'Global Burden of Disease research and health data.',u:'https://www.healthdata.org'},
  {n:'World Bank — Health',d:'Health financing, systems research and global data.',u:'https://www.worldbank.org/en/topic/health'},
 ]},
{id:'international',glyph:'🌍',name:'International',desc:'Multilateral institutions that set global norms, data and development finance.',
 sources:[
  {n:'United Nations',d:'Charter bodies, resolutions and the UN\'s official record.',u:'https://www.un.org'},
  {n:'World Bank',d:'Development finance, country data and global economic reports.',u:'https://www.worldbank.org'},
  {n:'International Monetary Fund',d:'Global macroeconomic surveillance, lending and financial stability.',u:'https://www.imf.org'},
  {n:'OECD',d:'Economic data and policy analysis across member economies.',u:'https://www.oecd.org'},
  {n:'UNESCO',d:'Education, science and culture — global standards and reports.',u:'https://www.unesco.org'},
  {n:'UNDP',d:'Human development data, including the Human Development Index.',u:'https://www.undp.org'},
  {n:'FAO',d:'Food and Agriculture Organization — food security and agri data.',u:'https://www.fao.org'},
  {n:'World Trade Organization',d:'Global trade rules, disputes and tariff data.',u:'https://www.wto.org'},
  {n:'UNHCR',d:'UN Refugee Agency — displacement data and protection standards.',u:'https://www.unhcr.org'},
  {n:'International Labour Organization',d:'Global labour standards, employment and wage data.',u:'https://www.ilo.org'},
  {n:'UNCTAD',d:'UN body on trade, investment and development policy.',u:'https://unctad.org'},
  {n:'UN Human Rights Office',d:'Monitoring and standard-setting on human rights globally.',u:'https://www.ohchr.org'},
  {n:'International Atomic Energy Agency',d:'Nuclear safety, safeguards and energy cooperation.',u:'https://www.iaea.org'},
  {n:'UN Environment Programme',d:'Global environmental policy coordination and data.',u:'https://www.unep.org'},
  {n:'World Economic Forum',d:'Global risk, competitiveness and economic policy reporting.',u:'https://www.weforum.org'},
  {n:'European Union',d:'Official portal for EU institutions, law and policy.',u:'https://european-union.europa.eu'},
  {n:'ASEAN',d:'Association of Southeast Asian Nations — regional cooperation.',u:'https://asean.org'},
  {n:'African Union',d:'Continental political and economic integration body.',u:'https://au.int'},
  {n:'NATO',d:'North Atlantic Treaty Organization — collective defence alliance.',u:'https://www.nato.int'},
  {n:'SAARC',d:'South Asian Association for Regional Cooperation.',u:'https://www.saarc-sec.org'},
  {n:'The Commonwealth',d:'Voluntary association of 56 member states.',u:'https://thecommonwealth.org'},
  {n:'INTERPOL',d:'International police cooperation and cross-border crime data.',u:'https://www.interpol.int'},
  {n:'Bank for International Settlements',d:'Central bank cooperation and global financial stability data.',u:'https://www.bis.org'},
  {n:'Asian Development Bank',d:'Regional development finance and economic research for Asia.',u:'https://www.adb.org'},
  {n:'UN OCHA',d:'Coordinates global humanitarian emergency response.',u:'https://www.unocha.org'},
  {n:'IRENA',d:'International Renewable Energy Agency — clean energy data.',u:'https://www.irena.org'},
  {n:'World Meteorological Organization',d:'Global weather, climate and water resource data.',u:'https://public.wmo.int'},
  {n:'International Organization for Migration',d:'UN agency on migration policy and data.',u:'https://www.iom.int'},
 ]},
{id:'reports',glyph:'📄',name:'Reports',desc:'The flagship official reports and audits that anchor most serious research.',
 sources:[
  {n:'Economic Survey',d:'Annual government assessment of economic performance and outlook.',u:'https://www.indiabudget.gov.in/economicsurvey/'},
  {n:'Union Budget Documents',d:'Full annual budget papers, demand for grants and receipts.',u:'https://www.indiabudget.gov.in'},
  {n:'CAG Reports',d:'Comptroller and Auditor General\'s audits of government spending.',u:'https://cag.gov.in'},
  {n:'NFHS',d:'National Family Health Survey — India\'s core demographic and health data.',u:'https://rchiips.org/nfhs/'},
  {n:'ASER',d:'Annual Status of Education Report — rural learning outcomes.',u:'https://asercentre.org'},
  {n:'PLFS',d:'Periodic Labour Force Survey — official employment statistics.',u:'https://www.mospi.gov.in/periodic-labour-force-survey-plfs'},
  {n:'Census of India',d:'The decennial national census and its official data releases.',u:'https://censusindia.gov.in'},
  {n:'NCRB',d:'National Crime Records Bureau — official crime statistics.',u:'https://ncrb.gov.in'},
  {n:'World Development Report',d:'World Bank\'s flagship annual development-policy report.',u:'https://www.worldbank.org/en/publication/wdr'},
  {n:'Human Development Report',d:'UNDP\'s annual ranking and analysis of human development.',u:'https://hdr.undp.org'},
  {n:'World Economic Outlook',d:'IMF\'s biannual global macroeconomic forecast and analysis.',u:'https://www.imf.org/en/Publications/WEO'},
  {n:'Global Gender Gap Report',d:'WEF\'s annual measure of gender parity across countries.',u:'https://www.weforum.org/publications/global-gender-gap-report/'},
  {n:'World Happiness Report',d:'Annual ranking of national wellbeing and life satisfaction.',u:'https://worldhappiness.report'},
  {n:'HRW World Report',d:'Human Rights Watch\'s annual review of rights conditions worldwide.',u:'https://www.hrw.org/world-report'},
  {n:'Corruption Perceptions Index',d:'Transparency International\'s annual public-sector corruption ranking.',u:'https://www.transparency.org/en/cpi'},
  {n:'Freedom in the World',d:'Freedom House\'s annual assessment of political rights globally.',u:'https://freedomhouse.org/report/freedom-world'},
  {n:'SIPRI Yearbook',d:'Stockholm institute\'s annual review of arms, disarmament and security.',u:'https://www.sipri.org'},
  {n:'Global Hunger Index',d:'Annual multidimensional measure of hunger at global and national levels.',u:'https://www.globalhungerindex.org'},
  {n:'State of the World\'s Children',d:'UNICEF\'s flagship annual report on child wellbeing.',u:'https://www.unicef.org/reports/state-worlds-children'},
  {n:'IPCC Reports',d:'The UN climate panel\'s assessment reports on climate science.',u:'https://www.ipcc.ch'},
  {n:'Global Risks Report',d:'WEF\'s annual mapping of the world\'s top systemic risks.',u:'https://www.weforum.org/publications/global-risks-report-2025/'},
  {n:'NITI Aayog SDG India Index',d:'Tracks state-wise progress on the Sustainable Development Goals.',u:'https://www.niti.gov.in/sdg-india-index'},
  {n:'RBI Annual Report',d:'The central bank\'s yearly report on the economy and its own operations.',u:'https://www.rbi.org.in/scripts/AnnualReportPublications.aspx'},
  {n:'India State of Forest Report',d:'Forest Survey of India\'s biennial forest-cover assessment.',u:'https://fsi.nic.in'},
  {n:'World Press Freedom Index',d:'Reporters Without Borders\' annual press-freedom ranking.',u:'https://rsf.org/en/index'},
  {n:'UNODC World Drug Report',d:'The UN\'s annual global assessment of drug production and use.',u:'https://www.unodc.org/unodc/en/data-and-analysis/wdr.html'},
 ]},
{id:'thinktanks',glyph:'🧠',name:'Think Tanks',desc:'Independent research institutions producing policy analysis grounded in data.',
 sources:[
  {n:'NITI Aayog',d:'Government policy think tank — strategy papers and dashboards.',u:'https://www.niti.gov.in'},
  {n:'PRS Legislative Research',d:'Non-partisan legislative and budget analysis.',u:'https://prsindia.org'},
  {n:'Observer Research Foundation',d:'Foreign policy, security and economic policy research.',u:'https://www.orfonline.org'},
  {n:'Centre for Policy Research',d:'Independent research on governance and public policy.',u:'https://www.cprindia.org'},
  {n:'ICRIER',d:'Economic policy research, trade and international economics.',u:'https://icrier.org'},
  {n:'Manohar Parrikar IDSA',d:'Defence and strategic studies research institute.',u:'https://www.idsa.in'},
  {n:'Brookings Institution',d:'U.S.-based public policy research across economics and foreign affairs.',u:'https://www.brookings.edu'},
  {n:'Carnegie Endowment for International Peace',d:'Global affairs and international security research.',u:'https://carnegieendowment.org'},
  {n:'Chatham House',d:'Independent policy institute on international affairs.',u:'https://www.chathamhouse.org'},
  {n:'RAND Corporation',d:'Nonpartisan research on defence, policy and global challenges.',u:'https://www.rand.org'},
  {n:'Council on Foreign Relations',d:'U.S. foreign policy research and analysis.',u:'https://www.cfr.org'},
  {n:'CSIS',d:'Center for Strategic and International Studies — global security research.',u:'https://www.csis.org'},
  {n:'Peterson Institute for International Economics',d:'Independent research on international economic policy.',u:'https://www.piie.com'},
  {n:'World Resources Institute',d:'Research on environment, climate and natural resources.',u:'https://www.wri.org'},
  {n:'International Crisis Group',d:'Conflict prevention and resolution research.',u:'https://www.crisisgroup.org'},
  {n:'Pew Research Center',d:'Nonpartisan public-opinion and social-trends research.',u:'https://www.pewresearch.org'},
  {n:'Gateway House',d:'Indian Council on Global Relations — foreign policy research.',u:'https://www.gatewayhouse.in'},
  {n:'Centre for Science and Environment',d:'India\'s leading environmental policy research body.',u:'https://www.cseindia.org'},
  {n:'Takshashila Institution',d:'India-focused public policy research and education.',u:'https://takshashila.org.in'},
  {n:'Vivekananda International Foundation',d:'Strategic and foreign-policy research institution.',u:'https://www.vifindia.org'},
  {n:'NCAER',d:'National Council of Applied Economic Research — India\'s oldest economic think tank.',u:'https://www.ncaer.org'},
  {n:'Lowy Institute',d:'Australian think tank on international policy.',u:'https://www.lowyinstitute.org'},
  {n:'Bruegel',d:'Brussels-based think tank on European economic policy.',u:'https://www.bruegel.org'},
  {n:'German Marshall Fund',d:'Transatlantic policy research institution.',u:'https://www.gmfus.org'},
  {n:'Stimson Center',d:'Research on peace, security and global risk reduction.',u:'https://www.stimson.org'},
  {n:'Wilson Center',d:'Nonpartisan policy forum on global affairs.',u:'https://www.wilsoncenter.org'},
 ]},
{id:'data',glyph:'📊',name:'Data',desc:'Raw, structured statistical datasets — the numbers behind every claim.',
 sources:[
  {n:'MOSPI',d:'National statistical office — GDP, CPI, IIP and survey data.',u:'https://www.mospi.gov.in'},
  {n:'Open Government Data Platform',d:'Searchable open datasets across every government sector.',u:'https://data.gov.in'},
  {n:'Census of India',d:'Population, household and demographic datasets.',u:'https://censusindia.gov.in'},
  {n:'PLFS',d:'Labour force participation and unemployment microdata.',u:'https://www.mospi.gov.in/periodic-labour-force-survey-plfs'},
  {n:'NFHS',d:'Health, nutrition and family welfare survey microdata.',u:'https://rchiips.org/nfhs/'},
  {n:'NCRB',d:'Crime and prisons statistics by state and category.',u:'https://ncrb.gov.in'},
  {n:'World Bank Open Data',d:'Free and open global development indicators.',u:'https://data.worldbank.org'},
  {n:'UN Data',d:'Aggregated statistics from across the UN system.',u:'https://data.un.org'},
  {n:'IMF Data',d:'Macroeconomic and financial statistics by country.',u:'https://www.imf.org/en/Data'},
  {n:'OECD Data',d:'Comparative statistics across OECD member economies.',u:'https://data.oecd.org'},
  {n:'Our World in Data',d:'Long-run global datasets visualised across major issues.',u:'https://ourworldindata.org'},
  {n:'Kaggle Datasets',d:'Open datasets and data-science competitions.',u:'https://www.kaggle.com/datasets'},
  {n:'Google Dataset Search',d:'Search engine indexing datasets across the open web.',u:'https://datasetsearch.research.google.com'},
  {n:'UNESCO Institute for Statistics',d:'Global education, science and culture statistics.',u:'http://uis.unesco.org'},
  {n:'Gapminder',d:'Long-term global development data and visualisation tools.',u:'https://www.gapminder.org'},
  {n:'WHO Global Health Observatory',d:'WHO\'s central repository of global health statistics.',u:'https://www.who.int/data/gho'},
  {n:'FAOSTAT',d:'Food and agriculture statistics from the FAO.',u:'https://www.fao.org/faostat'},
  {n:'ILOSTAT',d:'Global labour statistics database from the ILO.',u:'https://ilostat.ilo.org'},
  {n:'U.S. Census Bureau',d:'American demographic, economic and population data.',u:'https://www.census.gov'},
  {n:'Eurostat',d:'Official statistical office of the European Union.',u:'https://ec.europa.eu/eurostat'},
  {n:'World Inequality Database',d:'Global data on income and wealth inequality.',u:'https://wid.world'},
  {n:'UN SDG Indicators Database',d:'Official global tracking data for the Sustainable Development Goals.',u:'https://unstats.un.org/sdgs'},
  {n:'India Data Portal',d:'Curated Indian socioeconomic datasets and dashboards.',u:'https://indiadataportal.com'},
  {n:'NITI Aayog — NDAP',d:'National Data & Analytics Platform for public policy data.',u:'https://ndap.niti.gov.in'},
  {n:'DataMeet',d:'India\'s open-data community maintaining public datasets.',u:'https://datameet.org'},
  {n:'Humanitarian Data Exchange',d:'UN OCHA\'s open platform for humanitarian data sharing.',u:'https://data.humdata.org'},
  {n:'Global Data Lab',d:'Subnational human-development data for policy research.',u:'https://globaldatalab.org'},
  {n:'Population Reference Bureau',d:'Independent demographic data and population research.',u:'https://www.prb.org'},
 ]},
{id:'research',glyph:'🔬',name:'Research',desc:'Where the underlying scholarship, citation trails, and India\'s own research infrastructure live.',
 sources:[
  {n:'Google Scholar',d:'Search engine for scholarly literature across all disciplines.',u:'https://scholar.google.com'},
  {n:'Crossref',d:'Official DOI registry linking research metadata across publishers.',u:'https://www.crossref.org'},
  {n:'SSRN',d:'Preprint repository, strong in economics, law and social science.',u:'https://www.ssrn.com'},
  {n:'DOAJ',d:'Directory of Open Access Journals — vetted, free-to-read research.',u:'https://doaj.org'},
  {n:'PubMed',d:'The National Library of Medicine\'s biomedical literature index.',u:'https://pubmed.ncbi.nlm.nih.gov'},
  {n:'JSTOR',d:'Digital library of academic journals, books and primary sources.',u:'https://www.jstor.org'},
  {n:'arXiv',d:'Open-access preprints in physics, math, computer science and more.',u:'https://arxiv.org'},
  {n:'ResearchGate',d:'Academic social network for sharing papers and research data.',u:'https://www.researchgate.net'},
  {n:'Semantic Scholar',d:'AI-powered search engine for scientific literature.',u:'https://www.semanticscholar.org'},
  {n:'ORCID',d:'Persistent digital identifiers for researchers worldwide.',u:'https://orcid.org'},
  {n:'Web of Science',d:'Citation index spanning sciences, social sciences and humanities.',u:'https://www.webofscience.com'},
  {n:'Scopus',d:'Elsevier\'s abstract and citation database of peer-reviewed literature.',u:'https://www.scopus.com'},
  {n:'CORE',d:'World\'s largest aggregator of open-access research papers.',u:'https://core.ac.uk'},
  {n:'PLOS',d:'Nonprofit open-access science and medicine publisher.',u:'https://plos.org'},
  {n:'Springer',d:'Major academic publisher across science, technology and medicine.',u:'https://www.springer.com'},
  {n:'ScienceDirect',d:'Elsevier\'s platform for peer-reviewed journals and books.',u:'https://www.sciencedirect.com'},
  {n:'Shodhganga',d:'India\'s repository of PhD theses and dissertations.',u:'https://shodhganga.inflibnet.ac.in'},
  {n:'INFLIBNET',d:'Consortium providing digital library access to Indian universities.',u:'https://www.inflibnet.ac.in'},
  {n:'CSIR',d:'Council of Scientific & Industrial Research — India\'s applied research network.',u:'https://www.csir.res.in'},
  {n:'Department of Science & Technology',d:'India\'s national science policy and funding body.',u:'https://dst.gov.in'},
  {n:'Department of Biotechnology',d:'India\'s biotech research funding and regulatory body.',u:'https://dbtindia.gov.in'},
  {n:'ISRO',d:'India\'s space research organisation and mission archive.',u:'https://www.isro.gov.in'},
  {n:'Department of Atomic Energy',d:'India\'s nuclear science research and power programme.',u:'https://dae.gov.in'},
  {n:'U.S. National Academy of Sciences',d:'Independent advisory body on science and technology.',u:'https://www.nasonline.org'},
  {n:'The Royal Society',d:'UK\'s national academy of sciences, founded 1660.',u:'https://royalsociety.org'},
  {n:'DOAB',d:'Directory of Open Access Books — vetted, free-to-read academic books.',u:'https://www.doabooks.org'},
 ]},
];
